### ISSUE TITLE
~removeChangelog ERROR

### ISSUE THREAD

**Issue by MaDaWa404** [Akkjon/GummiBot#65]
[18.02.2021 - 11:32:18] [JDA MainWS-ReadThread] ERROR JDA - One of the EventListeners had an uncaught exception
[18.02.2021 - 11:32:18] java.lang.UnsupportedOperationException: remove
[18.02.2021 - 11:32:18] 	at java.base/java.util.Iterator.remove(Iterator.java:102)
[18.02.2021 - 11:32:18] 	at java.base/java.util.AbstractCollection.remove(AbstractCollection.java:283)
[18.02.2021 - 11:32:18] 	at de.akkjon.pr.mbrm.Commands.lambda$static$14(Commands.java:395)
[18.02.2021 - 11:32:18] 	at de.akkjon.pr.mbrm.Command.run(Command.java:37)
[18.02.2021 - 11:32:18] 	at de.akkjon.pr.mbrm.Commands.runCommands(Commands.java:436)
[18.02.2021 - 11:32:18] 	at de.akkjon.pr.mbrm.ServerWatcher$1.onMessageReceived(ServerWatcher.java:114)

**Comment by Akkjon** [comment]
och ich hasse es... ist wahrscheinlich einfach Arrays.asList anstatt new ArrayList<String>(Arrays.asList())
